### ISSUE TITLE
fetch_events_count should return a u64 to make it composable with fetch_event etc

### ISSUE THREAD

**Issue by marijanp** [koxu1996/casper-event-toolkit#2]
https://github.com/koxu1996/casper-event-toolkit/blob/fdfcc2105b524d2f7d2a557c45363822f19a01e0/src/fetcher.rs#L19

**Comment by koxu1996** [comment]
Nice catch! Instead of returning larger type in `fetch_events_count()`, it's better to use smaller type for fetching events - fixed in https://github.com/koxu1996/casper-event-toolkit/commit/58cc58284e5ca40670a578de40e39b3110039b83.
